---
- name: Reload network manager configuration
  ansible.builtin.command: /usr/bin/nmcli connection reload
  changed_when: true

- name: Reapply network configuration  # noqa: no-handler
  ansible.builtin.command: /usr/bin/nmcli device reapply {{
    item.invocation.module_args.ifname }}
  when: item.changed
  changed_when: true
  loop: '{{ configure_network_results.results }}'
  loop_control:
    label: '{{ item.invocation.module_args.conn_name }}'
