---
nmcli_connections:
  - conn_name: net1
    ifname: eth1
    ip4: '192.168.10.1/24'
  - conn_name: r1-r2
    ifname: eth2
    ip4: '10.0.10.1/30'
  - conn_name: r1-r3
    ifname: eth3
    ip4: '10.0.12.1/30'

frr_ospf_iface_cost:
  eth2: 10000
